version: "3.7"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
  app:
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mongo
